### ISSUE TITLE
Define an API key using Docker Compose

### ISSUE THREAD

**Issue by hakrishi** [sundowndev/phoneinfoga#1235]
Hello,

How do I define an API key using docker compose? Here is my current compose file:
```
version: '3.7'

services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: on-failure
      image: sundowndev/phoneinfoga:latest
      command:
        - "serve"
      ports:
        - "80:5000"
```

I'd like to add a key for NumVerify. 

Thanks
