### ISSUE TITLE
Unable to access web GUI

### ISSUE THREAD

**Issue by hakrishi** [sundowndev/phoneinfoga#1260]
**Describe the bug**
Web page not being hosted on port 5000

**To Reproduce**
Copy the docker-compose file from the docs:
```
version: '3.7'
services:
    phoneinfoga:
      container_name: phoneinfoga
      restart: on-failure
      image: sundowndev/phoneinfoga:latest
      command:
        - "serve"
      ports:
        - "80:5000"
```
Then ran`docker-compose up -d`

**Expected behavior**
I should be able to access the web page.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/59293085/233770157-d3f43468-9aeb-4263-8378-dfb866468cb2.png)
![image](https://user-images.githubusercontent.com/59293085/233770221-daf3260f-f06c-40ce-9380-4a8546d8c4a7.png)
![image](https://user-images.githubusercontent.com/59293085/233770245-15b68c4c-41bc-4cfc-a68c-7bcf2f18bad1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - PhoneInfoga exact version: Unable to find out as I am unable to connect to the container
 - Go exact version Unable to find out as I am unable to connect to the container
