### ISSUE TITLE
Add Environment vars to Docker Compose

### ISSUE THREAD

**Issue by STaRDoGG** [sundowndev/phoneinfoga#1370]
**Describe the bug**

For us Docker "prefer-ers" so to speak, it would be convenient to be able to add our `.env` configs right to the Docker Compose.

i.e.

```
    environment:
      TZ: 'America/Chicago'
      NUMVERIFY_API_KEY: 'value'
      GOOGLECSE_CX: 'value'
      GOOGLE_API_KEY: 'value'
```

Currently, I just/have to mount the `.env` file like:

```
    volumes:
      - '/opt/docker/configs/phoneinfoga/.env:/.env:ro'
```

Which isn't horrible, but a bit less convenient to have to go digging into the file system to edit, etc. rather than just do it all right in the Docker config.

**Additional context**

tis all! =)
