### ISSUE TITLE
[Feature][Docker] Add CLI argument for `listen_address`

### ISSUE THREAD

**Issue by ToshY** [sundowndev/PhoneInfoga#1461]
**Problem**

Currently, with a default docker setup, the `phoneinfoga` container does not have an option to set the listen address to for example `0.0.0.0` to allow connections from other containers. This leads to external containers like `waisbrot/wait` to fail when determining the status of the `phoneinfoga` container.

<details><summary><code>compose.yaml</code></summary>

```yaml
x-restart: &restart-stopped
  restart: unless-stopped

name: phoneinfoga
services:
  phoneinfoga:
    image: sundowndev/phoneinfoga:${PHONEINFOGA_IMAGE_VERSION:-latest}
    <<: [*restart-stopped]
    command: serve
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:5000/api | grep -q '\"success\":true'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.phoneinfoga.tls: true
      traefik.http.routers.phoneinfoga.entrypoints: websecure
      traefik.http.routers.phoneinfoga.rule: Host(`${PHONEINFOGA_URL:?}`)
      traefik.http.routers.phoneinfoga.service: phoneinfoga
      traefik.http.services.phoneinfoga.loadbalancer.server.port: 5000
    networks:
      - phoneinfoga
      - proxy

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: phoneinfoga:5000
      TIMEOUT: 30
    networks:
      - phoneinfoga

networks:
  phoneinfoga:
    driver: bridge
  proxy:
    external: true

```

```shell
docker compose up -d --build --force-recreate --remove-orphans --pull always
docker compose run --rm wait
```

> **NOTE**
> The `healtcheck` currently works, but the container cannot be pinged from the `wait` service.

</details> 

**Suggestion**

Add CLI arg for `address` / `listen-address` / `listen_address` to allow usage of `0.0.0.0`.
